/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as BibleIndexRouteImport } from './routes/bible.index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as BibleBookIdChapterRouteImport } from './routes/bible.$bookId.$chapter'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookIdChapterRoute = BibleBookIdChapterRouteImport.update({
  id: '/bible/$bookId/$chapter',
  path: '/bible/$bookId/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/profil': typeof ProfilRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible/': typeof BibleIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/profil': typeof ProfilRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible': typeof BibleIndexRoute
  '/plans': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/profil': typeof ProfilRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible/': typeof BibleIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/profil'
    | '/plans/$planId'
    | '/bible/'
    | '/plans/'
    | '/bible/$bookId/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/profil'
    | '/plans/$planId'
    | '/bible'
    | '/plans'
    | '/bible/$bookId/$chapter'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/profil'
    | '/plans/$planId'
    | '/bible/'
    | '/plans/'
    | '/bible/$bookId/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  FavorisRoute: typeof FavorisRoute
  ProfilRoute: typeof ProfilRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  BibleIndexRoute: typeof BibleIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  BibleBookIdChapterRoute: typeof BibleBookIdChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$bookId/$chapter': {
      id: '/bible/$bookId/$chapter'
      path: '/bible/$bookId/$chapter'
      fullPath: '/bible/$bookId/$chapter'
      preLoaderRoute: typeof BibleBookIdChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  FavorisRoute: FavorisRoute,
  ProfilRoute: ProfilRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  BibleIndexRoute: BibleIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  BibleBookIdChapterRoute: BibleBookIdChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
