/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as BibleIndexRouteImport } from './routes/bible.index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as BibleBookIdChapterRouteImport } from './routes/bible.$bookId.$chapter'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookIdChapterRoute = BibleBookIdChapterRouteImport.update({
  id: '/bible/$bookId/$chapter',
  path: '/bible/$bookId/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/meditation': typeof MeditationRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible/': typeof BibleIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/meditation': typeof MeditationRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible': typeof BibleIndexRoute
  '/plans': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/meditation': typeof MeditationRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/bible/': typeof BibleIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/bible/$bookId/$chapter': typeof BibleBookIdChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/forgot-password'
    | '/historique'
    | '/meditation'
    | '/profil'
    | '/reset-password'
    | '/plans/$planId'
    | '/bible/'
    | '/plans/'
    | '/bible/$bookId/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/forgot-password'
    | '/historique'
    | '/meditation'
    | '/profil'
    | '/reset-password'
    | '/plans/$planId'
    | '/bible'
    | '/plans'
    | '/bible/$bookId/$chapter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/assistant'
    | '/auth'
    | '/favoris'
    | '/forgot-password'
    | '/historique'
    | '/meditation'
    | '/profil'
    | '/reset-password'
    | '/plans/$planId'
    | '/bible/'
    | '/plans/'
    | '/bible/$bookId/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  FavorisRoute: typeof FavorisRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoriqueRoute: typeof HistoriqueRoute
  MeditationRoute: typeof MeditationRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  BibleIndexRoute: typeof BibleIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  BibleBookIdChapterRoute: typeof BibleBookIdChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$bookId/$chapter': {
      id: '/bible/$bookId/$chapter'
      path: '/bible/$bookId/$chapter'
      fullPath: '/bible/$bookId/$chapter'
      preLoaderRoute: typeof BibleBookIdChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  FavorisRoute: FavorisRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoriqueRoute: HistoriqueRoute,
  MeditationRoute: MeditationRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  BibleIndexRoute: BibleIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  BibleBookIdChapterRoute: BibleBookIdChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
